/*

   <SYNONYM>
        SYNONYM은 오라클에서 제공하는 객체로 데이터베이스 객체에 별칭을 생성한다.

        1. 

*/
-- 관리자 계정으로 KH 계정에 SYNONYM 생성 권한을 준다.
GRANT CREATE SYNONYM TO KH;

SELECT * 
FROM ROLE_SYS_PRIVS
WHERE ROLE = 'RESOURCE';

-- EMPLOYEE 테이블에 EMP 비공개 SYNONYM 생성
CREATE SYNONYM EMP FOR EMPLOYEE;

SELECT * FROM EMP;

CREATE SYNONYM QU FOR BK_NO_PK;
DROP SYNONYM QU;


GRANT CREATE SYNONYM TO STUDY;
CREATE SYNONYM CNTST FOR STU_COUNT_BY_DEPT;
DROP SYNONYM CNTST;



-- 2. 공개 SYNONYM 생성
-- 관리자 계정으로 접속하여 공개 SYNONYM 생성
CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
DROP PUBLIC SYNONYM DEPT;

-- 관리자 계정으로 다른 사용자 계정에서 테이블에 접근할 수 있는 권한을 준다.
GRANT SELECT ON KH.DEPARTMENT TO STUDY;


SELECT * FROM KH.DEPARTMENT;
SELECT * FROM DEPT;