-- 테이블 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_GRADE;
DROP TABLE EMP_COPY;
DROP TABLE DEPT_COPY;

-- 테이블 생성
CREATE TABLE MEMBER (
    NO          NUMBER,
    ID          VARCHAR2(20) NOT NULL,
    PASSWORD    VARCHAR2(20) NOT NULL,
    NAME        VARCHAR2(15) NOT NULL,
    GENDER      CHAR(3),
    AGE         NUMBER,
    GRADE_ID    NUMBER
        CONSTRAINT MEMBER_GRADE_ID_FK
            REFERENCES MEMBER_GRADE
                ON DELETE CASCADE,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT MEMBER_NO_PK PRIMARY KEY ( NO ),
    CONSTRAINT MEMBER_ID_UQ UNIQUE ( ID ),
    CONSTRAINT MEMBER_GENDER_CK CHECK ( GENDER IN ( '남', '여' ) ),
    CONSTRAINT MEMBER_AGE_CK CHECK ( AGE > 0 ));

-- MEMBER_GRADE
CREATE TABLE MEMBER_GRADE (
    GRADE_CODE NUMBER PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL
);


-- 테이블 확인
SELECT * FROM MEMBER;
SELECT * FROM MEMBER_GRADE;

-- 제약조건 확인하는 뷰 테이블
SELECT UC.CONSTRAINT_NAME, UC.TABLE_NAME, UCC.COLUMN_NAME, UCC.POSITION, UC.CONSTRAINT_TYPE
FROM   USER_CONSTRAINTS UC INNER JOIN USER_CONS_COLUMNS UCC ON ( UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME )
WHERE  UC.TABLE_NAME = 'MEMBER';

-- VALUE 추가
   -- MEMBER
INSERT INTO MEMBER VALUES (1, 'USER1', '1234', '문인수', '남', 22, 10, DEFAULT);
INSERT INTO MEMBER VALUES (2, 'USER2', '1234', '홍길동', '남', 30, NULL, DEFAULT);
INSERT INTO MEMBER VALUES (3, 'USER3', '1234', '홍길동', '남', 22, 10, DEFAULT);
    -- MEMBER_GRADE
INSERT INTO MEMBER_GRADE VALUES (10, '일반회원');
INSERT INTO MEMBER_GRADE VALUES (20, '우수회원');
INSERT INTO MEMBER_GRADE VALUES (30, '특별회원');

-- 커밋
COMMIT;

-- 롤백
ROLLBACK;